package io.github.bitaron.filemanager.core.file;

import java.time.Instant;
import java.util.UUID;

import io.github.bitaron.filemanager.core.Actor;
import io.github.bitaron.filemanager.core.tenant.TenantId;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.Table;

import lombok.AccessLevel;
import lombok.Getter;
import lombok.NoArgsConstructor;

/**
 * A Tenant-scoped unit of stored content, belonging to exactly one Folder (see the glossary in
 * {@code CONTEXT.md}). Field list is normative per ADR 0003 - don't add columns without updating
 * that ADR.
 *
 * <p>Unlike {@code Folder}'s nullable parent, {@link #getParentFolderId()} is never {@code null} -
 * every File belongs to exactly one Folder (ADR 0003).
 *
 * <p>This entity exposes read accessors only - no setters - per docs/architecture.md's "service
 * interfaces, not entity setters" rule. All mutation goes through {@link FileService}.
 */
@Entity
@Table(
        name = "file",
        // Same composite-index rationale as Folder's idx_folder_tenant_parent: a
        // (tenant_id, parent_folder_id) index serves both "list a Folder's Files" (ticket #34)
        // and any tenant_id-only lookup as a left-prefix, so no separate single-column index is
        // needed on top of it.
        indexes = @Index(name = "idx_file_tenant_parent", columnList = "tenant_id, parent_folder_id"))
@NoArgsConstructor(access = AccessLevel.PROTECTED)
public class File {

    // Not final: JPA providers hydrate these fields via reflection on the protected no-arg
    // constructor above. Outside that, this class exposes no setters - only the package-private
    // constructor FileService uses. tenantId/createdBy/lastModifiedBy/trashedBy have no
    // generated getter of their own - callers get them wrapped as TenantId/Actor via the methods
    // below, not as raw UUIDs (matching Folder's/ApiKey's convention).
    @Id
    @Column(name = "id", nullable = false, updatable = false)
    @Getter
    private UUID id;

    // FK -> tenant(id) per ADR 0003, enforced at the schema-DDL level, not as a JPA
    // @ManyToOne - core has no need to navigate to the Tenant entity here (matches Folder's/
    // ApiKey's convention).
    @Column(name = "tenant_id", nullable = false, updatable = false)
    private UUID tenantId;

    /** Every File belongs to exactly one Folder - unlike Folder's nullable parent (ADR 0003). */
    @Column(name = "parent_folder_id", nullable = false)
    @Getter
    private UUID parentFolderId;

    @Column(name = "name", nullable = false)
    @Getter
    private String name;

    @Column(name = "size", nullable = false)
    @Getter
    private long size;

    @Column(name = "content_type", nullable = false)
    @Getter
    private String contentType;

    @Column(name = "visibility", nullable = false)
    @Enumerated(EnumType.STRING)
    @Getter
    private Visibility visibility;

    /**
     * The opaque reference {@link io.github.bitaron.filemanager.storage.StorageBackend#store}
     * returned for this File's content - never interpreted by {@code core} (ADR 0002). No public
     * getter: it must never leak past this package, let alone into a DTO.
     */
    @Column(name = "storage_reference", nullable = false)
    private String storageReference;

    @Column(name = "created_at", nullable = false, updatable = false)
    @Getter
    private Instant createdAt;

    /** Opaque Actor reference - no DB-level foreign key (ADR 0003, decision #10). */
    @Column(name = "created_by", nullable = false, updatable = false)
    private UUID createdBy;

    @Column(name = "updated_at", nullable = false)
    @Getter
    private Instant updatedAt;

    /** Opaque Actor reference - no DB-level foreign key (ADR 0003, decision #10). */
    @Column(name = "last_modified_by", nullable = false)
    private UUID lastModifiedBy;

    @Column(name = "trashed_at")
    @Getter
    private Instant trashedAt;

    /** Opaque Actor reference - no DB-level foreign key (ADR 0003, decision #10). */
    @Column(name = "trashed_by")
    private UUID trashedBy;

    /**
     * @param id the File's own id, generated by the caller (not internally, unlike {@code Folder})
     *     because {@link FileService#upload} needs it as the {@code StorageBackend} key *before*
     *     this constructor runs - see that method's javadoc.
     */
    File(UUID id, TenantId tenantId, UUID parentFolderId, String name, long size, String contentType,
            Visibility visibility, String storageReference, Actor actor, Instant now) {
        this.id = id;
        this.tenantId = tenantId.id();
        this.parentFolderId = parentFolderId;
        this.name = name;
        this.size = size;
        this.contentType = contentType;
        this.visibility = visibility;
        this.storageReference = storageReference;
        this.createdAt = now;
        this.createdBy = actor.id();
        this.updatedAt = now;
        this.lastModifiedBy = actor.id();
    }

    /**
     * Renames this File in place - a single-row update, per ADR 0003/0004. No uniqueness check
     * against sibling names (ADR 0003: duplicate sibling names are legal).
     */
    void rename(String name, Actor actor, Instant now) {
        this.name = name;
        this.updatedAt = now;
        this.lastModifiedBy = actor.id();
    }

    /**
     * Re-parents this File in place - a single-row update, per ADR 0003/0004.
     *
     * @param parentFolderId the new parent Folder's id - never {@code null}, unlike
     *     {@code Folder.moveTo} (ADR 0003: every File belongs to exactly one Folder)
     */
    void moveTo(UUID parentFolderId, Actor actor, Instant now) {
        this.parentFolderId = parentFolderId;
        this.updatedAt = now;
        this.lastModifiedBy = actor.id();
    }

    /**
     * Trashes this File in place - a single-row update, per ADR 0003/0004. Mirrors
     * {@code Folder.trash} exactly.
     *
     * <p>Idempotent (issue #37): if this File is already trashed, this is a full no-op - none of
     * {@code trashedAt}/{@code trashedBy}/{@code updatedAt}/{@code lastModifiedBy} are touched, so
     * a redundant call never overwrites the original trash and never produces a spurious "last
     * modified" change.
     */
    void trash(Actor actor, Instant now) {
        if (trashedAt != null) {
            return;
        }
        this.trashedAt = now;
        this.trashedBy = actor.id();
        this.updatedAt = now;
        this.lastModifiedBy = actor.id();
    }

    /**
     * Restores this File in place - a single-row update, per ADR 0003/0004. Mirrors
     * {@code Folder.restore} exactly.
     *
     * <p>Idempotent (issue #37): if this File is already active (not trashed), this is a full
     * no-op - {@code updatedAt}/{@code lastModifiedBy} are left untouched too.
     */
    void restore(Actor actor, Instant now) {
        if (trashedAt == null) {
            return;
        }
        this.trashedAt = null;
        this.trashedBy = null;
        this.updatedAt = now;
        this.lastModifiedBy = actor.id();
    }

    public TenantId tenantId() {
        return new TenantId(tenantId);
    }

    public Actor createdBy() {
        return new Actor(createdBy);
    }

    public Actor lastModifiedBy() {
        return new Actor(lastModifiedBy);
    }

    /** {@code null} until this File is trashed. */
    public Actor trashedBy() {
        return trashedBy == null ? null : new Actor(trashedBy);
    }

    /** No public getter, per AGENT-BRIEF.md - storageReference must never leak past this package. */
    String getStorageReference() {
        return storageReference;
    }
}
